require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SuggestsController do

  # This should return the minimal set of attributes required to create a valid
  # Suggest. As you add validations to Suggest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "article" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SuggestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all suggests as @suggests" do
      suggest = Suggest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:suggests).should eq([suggest])
    end
  end

  describe "GET show" do
    it "assigns the requested suggest as @suggest" do
      suggest = Suggest.create! valid_attributes
      get :show, {:id => suggest.to_param}, valid_session
      assigns(:suggest).should eq(suggest)
    end
  end

  describe "GET new" do
    it "assigns a new suggest as @suggest" do
      get :new, {}, valid_session
      assigns(:suggest).should be_a_new(Suggest)
    end
  end

  describe "GET edit" do
    it "assigns the requested suggest as @suggest" do
      suggest = Suggest.create! valid_attributes
      get :edit, {:id => suggest.to_param}, valid_session
      assigns(:suggest).should eq(suggest)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Suggest" do
        expect {
          post :create, {:suggest => valid_attributes}, valid_session
        }.to change(Suggest, :count).by(1)
      end

      it "assigns a newly created suggest as @suggest" do
        post :create, {:suggest => valid_attributes}, valid_session
        assigns(:suggest).should be_a(Suggest)
        assigns(:suggest).should be_persisted
      end

      it "redirects to the created suggest" do
        post :create, {:suggest => valid_attributes}, valid_session
        response.should redirect_to(Suggest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved suggest as @suggest" do
        # Trigger the behavior that occurs when invalid params are submitted
        Suggest.any_instance.stub(:save).and_return(false)
        post :create, {:suggest => { "article" => "invalid value" }}, valid_session
        assigns(:suggest).should be_a_new(Suggest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Suggest.any_instance.stub(:save).and_return(false)
        post :create, {:suggest => { "article" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested suggest" do
        suggest = Suggest.create! valid_attributes
        # Assuming there are no other suggests in the database, this
        # specifies that the Suggest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Suggest.any_instance.should_receive(:update).with({ "article" => "" })
        put :update, {:id => suggest.to_param, :suggest => { "article" => "" }}, valid_session
      end

      it "assigns the requested suggest as @suggest" do
        suggest = Suggest.create! valid_attributes
        put :update, {:id => suggest.to_param, :suggest => valid_attributes}, valid_session
        assigns(:suggest).should eq(suggest)
      end

      it "redirects to the suggest" do
        suggest = Suggest.create! valid_attributes
        put :update, {:id => suggest.to_param, :suggest => valid_attributes}, valid_session
        response.should redirect_to(suggest)
      end
    end

    describe "with invalid params" do
      it "assigns the suggest as @suggest" do
        suggest = Suggest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Suggest.any_instance.stub(:save).and_return(false)
        put :update, {:id => suggest.to_param, :suggest => { "article" => "invalid value" }}, valid_session
        assigns(:suggest).should eq(suggest)
      end

      it "re-renders the 'edit' template" do
        suggest = Suggest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Suggest.any_instance.stub(:save).and_return(false)
        put :update, {:id => suggest.to_param, :suggest => { "article" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested suggest" do
      suggest = Suggest.create! valid_attributes
      expect {
        delete :destroy, {:id => suggest.to_param}, valid_session
      }.to change(Suggest, :count).by(-1)
    end

    it "redirects to the suggests list" do
      suggest = Suggest.create! valid_attributes
      delete :destroy, {:id => suggest.to_param}, valid_session
      response.should redirect_to(suggests_url)
    end
  end

end
